name: Manylinux wheels

on:
  workflow_dispatch:
    # allow manual runs on branches without a PR

jobs:
  manylinux_wheel_create:
    env:
      CIBW_BUILD_VERBOSITY_LINUX: 3
      CIBW_BUILD:  ${{ matrix.cibw_build }}
      CIBW_ARCHS: ${{ matrix.cibw_archs }}
      CIBW_BEFORE_ALL_LINUX: >
        source .circleci/ubuntu_ci.sh &&
        install_manylinux_build_deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: x86_64
            cibw_build: 'cp37-manylinux_x86_64 cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64'
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.16.5
    - name: Make wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Upload wheels as artifact
      uses: actions/upload-artifact@v3
      with:
        name: manylinux_wheels
        path: ./wheelhouse/*.whl

  manylinux_wheel_upload:
    runs-on: ubuntu-latest
    needs: [manylinux_wheel_create]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: actions/download-artifact@v3
      with:
        name: manylinux_wheels
        path: dist
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: dist/*
        draft: true
