name: Wheels

on:
  workflow_dispatch:
    # allow manual runs on branches without a PR

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz


  build_ubuntu_wheels:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-22.04

    timeout-minutes: 180

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD: "cp311*-manylinux_x86_64*"

      - name: Upload wheels
        uses: actions/upload-artifact@v4.3.0
        with:
          name: wheels_ubuntu__${{ github.sha }}
          path: wheelhouse/*.whl
